name: Remove old package versions

jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ifargle/headscale-webui
          token: ${{ secrets.GITHUB_TOKEN }}