name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main  # 或者你想监听的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动生成的 token

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }} .

      # Push the Docker image to GitHub Container Registry (GHCR)
      - name: Push Docker image to GitHub Packages (GHCR)
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}
